[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/random-song"
  to = "/.netlify/functions/random-song"
  status = 200
